parameters:
  project:
    name: #
    target_root: #

  delivery:
    folder:
      parent: #
      sources: #
    suffix_format: _`date +'%Y%m%d'`

environments:
  list:
    - prod

  prod:
    name: #
    short: #
    suffix: #
    origin_branch: #
    deploy:
      type:  # src|sources/pkg|package
      user:  #
      host:  #
#      pass: ***
      target: #
#      commands:
#        before_scripts:
#        after_scripts :
